# Generated by Django 6.0.3 on 2026-03-20 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='password_token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
